name: Rust

on: [push]

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        - { os: windows-latest, target: x86_64-pc-windows-msvc, toolchain: 1.33.0 }
        - { os: windows-latest, target: i686-pc-windows-msvc, toolchain: 1.33.0 }
        - { os: windows-latest, target: x86_64-pc-windows-msvc, toolchain: stable }
        - { os: windows-latest, target: i686-pc-windows-msvc, toolchain: stable }
        - { os: windows-latest, target: x86_64-pc-windows-msvc, toolchain: beta }
        - { os: windows-latest, target: i686-pc-windows-msvc, toolchain: beta }
        - { os: macOS-latest, target: x86_64-apple-darwin, toolchain: 1.33.0 }
        - { os: macOS-latest, target: x86_64-apple-darwin, toolchain: stable }
        - { os: macOS-latest, target: x86_64-apple-darwin, toolchain: beta }
        - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu, toolchain: 1.33.0 }
        - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu, toolchain: stable }
        - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu, toolchain: beta }
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        target:  ${{ matrix.target }}
        profile: minimal
    # Note(Lokathor): We don't need to install SDL2 on windows, it's bundled.
    - name: Install SDL2 (if Mac)
      if: ${{ matrix.target }} == "x86_64-apple-darwin"
      run: brew update && brew install sdl2
    - name: Install SDL2 (if Linux)
      if: ${{ matrix.target }} == "x86_64-unknown-linux-gnu"
      run: sudo apt-get -qq install libsdl2-dev
    - name: Run Tests with Dynamic Link
      uses: actions-rs/cargo@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        command: test --feature="dynamic_link"
    - name: Run Tests with Static Link
      uses: actions-rs/cargo@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        command: test --feature="static_link"
